### ISSUE TITLE
compile-vunit scripts under/libraries/vendors no longer point to correct files

### ISSUE THREAD

**Issue by dbalthazor** [ghdl/ghdl#534] opened 2018-02-22 01:53 UTC
The VUnit update to from 2.4.3 to 3.0+ has moved around files in the vunit/vunit/vhdl/ folder such that the compile-vunit scripts no longer functions and does not compile the library. 

For example: 

-  vhdl/src/lang/lang.vhd no longer exists
-  core/src/stop_api.vhd no longer exists
-  Addition of data_types folder
-  Addition of random folder
-  Refactor has changed dependencies of modules

Sample output of ./compile-vunit.sh provided
- Run on Ubuntu 14.04LTS
- GHDL v0.3.5
- VUnit v3.0.1

https://pastebin.com/rs0cnZfP

**Comment by Paebbels** [comment] 2018-02-22 07:08
This is a duplicate of: [compile-vunit.sh incorrect source file directory reference](https://github.com/ghdl/ghdl/issues/528)

> The support of pre-compiled VUnit scripts will end soon. VUnit has it's own compilation routines, so no pre-compilation is needed.
> 
> **Do you have another use case to use stand-alone pre-compiled VUnit scripts?**

**Closed by Paebbels** 2018-02-22 07:08 UTC
