### ISSUE TITLE
external names

### ISSUE THREAD

**Issue by slaweksiluk** [ghdl/ghdl#548] opened 2018-03-29 20:25 UTC
Hello, please find below reproducer for vhdl2008 external names feature
```
ext-names> ghdl -a --std=08 tb.vhd 
translate_expression: cannot handle IIR_KIND_EXTERNAL_SIGNAL_NAME (tb.vhd:42:26)

******************** GHDL Bug occured ****************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 0.36-dev (v0.35-148-g156005b) [Dunoon edition]
Compiled with GNAT Version: 4.9.3
Target: x86_64-linux-gnu
In directory: /home/slawek/git/github/misc/vhdl-playground/ext-names/
Command line:
/home/slawek/install_prefix/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/ghdl1 --std=08 -P/home/slawek/install_prefix/lib/ghdl/ieee/v08/ -P/home/slawek/install_prefix/lib/ghdl/ -quiet -o tb.s tb.vhd
Exception TYPES.INTERNAL_ERROR raised
Exception information:
Exception name: TYPES.INTERNAL_ERROR
Message: errorout.adb:246
Call stack traceback locations:
0x6d1224 0x72e47f 0x75f138 0x765148 0x764d55 0x755528 0x78522b 0x74ae6d 0x78712a 0x6c3987 0x69affe 0xb64f2c 0x694ffc 0x6a0145 0x6c39d9 0x693725 0x7f60fddbd82e 0x6977e7 0xfffffffffffffffe
******************************************************************

Execution terminated by unhandled exception
Exception name: TYPES.INTERNAL_ERROR
Message: errorout.adb:246
Call stack traceback locations:
0x6d1224 0x72e47f 0x75f138 0x765148 0x764d55 0x755528 0x78522b 0x74ae6d 0x78712a 0x6c3987 0x69affe 0xb64f2c 0x694ffc 0x6a0145 0x6c39d9 0x693725 0x7f60fddbd82e 0x6977e7 0xfffffffffffffffe
ghdl:error: compilation error

```

```vhdl
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity dut is
    Port (
    	clk		: in std_logic
    );
end dut;
architecture dut_arch of dut is
	signal local_sig : std_logic;
begin
	proc: process begin
		local_sig <= '0';
		wait for 50 ns;
		local_sig <= '1';
	end process;
end dut_arch;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity tb is
end tb;
architecture tb_arch of tb is
	component dut is
	port
	(
		clk : in std_logic
	);
	end component;
	signal clk		: std_logic;
	signal tb_sig		: std_logic;
begin
	dut_inst : dut
	port map
	(
		clk => clk
	);

	proc: process begin
		wait for 50 ns;
		tb_sig <= << signal .tb.dut_inst.local_sig : std_logic >>;
	end process;
end tb_arch;
```

**Comment by tgingold** [comment] 2018-03-30 07:17
Thanks!  This feature is not yet implemented.

**Comment by GlenNicholls** [comment] 2019-10-17 15:10
What is the status on this VHDL2008 feature?

**Comment by tgingold** [comment] 2019-10-17 20:23
No progress yet.  I am a little bit busy with synthesis...

**Comment by csantosb** [comment] 2020-07-09 10:46
It would be great to have this feature, as this would allow doing remote in depth verification and debugging with help of non synthetisable ancillary libraries. 
As an alternative in the meantime, one may opt for the vpi interface.

**Comment by umarcor** [comment] 2020-07-09 13:29
@csantosb, related to https://github.com/umarcor/ghdl-cosim/blob/vhdl202x-lcd-dpi/vhdl202x-lcs-dpi/main.md, do you have any public example about remote verification and debugging?

**Comment by csantosb** [comment] 2020-07-09 20:15
@umarcor, by remote I meant logging and inspection of internal hierarchy signals from within the testbench. I'm using the vpi interface with help of cocotb.

**Comment by JimLewis** [comment] 2021-05-15 17:23
@tgingold   How is this feature coming?   

OSVVM needs external names to protected types.   It is how we are currently doing our BurstFifos.   I have test cases if you need them.

**Comment by maehne** [comment] 2021-05-17 16:36
This feature would be very helpful for writing advanced test benches that are able to monitor internal state of the DUT.

**Comment by tgingold** [comment] 2021-05-17 17:02
I think we all agree that this feature is helpful!

**Comment by miklhh** [comment] 2021-07-07 07:48
Leaving this comment to show my encouragement for adding this feature.

**Comment by JimLewis** [comment] 2021-08-07 17:09
Quick Update.   OSVVM was using external names for data structure access.   With the 2021.06 and 2021.07 releases, we created singleton data structures for Memory, Scoreboards, and Coverage.   As a result, we no longer need external names for these.      

OTOH, for our verification components that need a Virtual Transaction Interface - when the verification component is internal to the DUT, we are still using external names.    

So OSVVM has reduced the number of places where this problem is blocking usage of features.

**Comment by goekce** [comment] 2021-12-22 16:47
Isn't this a duplicate of https://github.com/ghdl/ghdl/issues/24?

**Comment by umarcor** [comment] 2021-12-23 00:23
@goekce it is. However, reproducers are different, and these features are not implemented all of a sudden. Hence, we keep some issues open and we close them when reproducers are added to the testsuite and can be succesfully handled. The same applies to generic types and unconstrained stuff:

- https://github.com/ghdl/ghdl/labels/FeaReq%3A%20VHDL-2008%20%28generic%20types%29
- https://github.com/ghdl/ghdl/labels/FeaReq%3A%20VHDL-2008%20%28unconst.%20arrrays%2Frecords%29

This is mostly because we don't have huge traffic in this repo, so it is affordable to have such granularity without creating too much confusion among "regular" users.

**Comment by vruizescribano** [comment] 2023-08-03 20:08
Hi everyone. 
I wonder if the external names has been implemented in the release ghdl 3.0.0
I was trying to use external names in self-checking verifications but I got a GHDL error similar to the one posted here.

`translate_expression: cannot handle IIR_KIND_EXTERNAL_SIGNAL_NAME
******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 3.0.0 (2.0.0.r1417.g7de967c51) [Dunoon edition]
Compiled with GNAT Version: Community 2019 (20190517-83)
Target: x86_64-apple-darwin17.7.0`

**Comment by umarcor** [comment] 2023-08-03 22:33
@vruizescribano I think it's not completely implemented yet. See https://github.com/ghdl/ghdl/labels/FeaReq%3A%20VHDL-2008%20%28external%20names%29. Feel free to open an issue with your own reproducer of the crash/bug.

**Closed** 2023-09-18 05:24 UTC
Labels: FeaReq: VHDL-2008 (external names)
