### ISSUE TITLE
GHDL crashes when trying to implement a shift register using an array type.

### ISSUE THREAD

**Issue by erick166** [ghdl/ghdl#2055] opened 2022-05-11 20:25 UTC
**How to reproduce?**
```
architecture func of tb is

  type   t_slv_array is array (natural range <>) of std_logic_vector;
  signal slv_array : t_slv_array(0 to 1)(9 downto 0);
  signal slv       : std_logic_vector(9 downto 0);

begin

  p_main : process
  begin

    slv_array <= slv_array(1) & slv;

    std.env.stop;
    wait;  -- to stop completely
  end process p_main;
end architecture func;
```

**Error message:**
```
******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 3.0.0-dev (2.0.0.r159.g98bc5e03) [Dunoon edition]
Compiled with GNAT Version: 11.3.0
Target: i686-w64-mingw32

Exception TYPES.INTERNAL_ERROR raised
Exception information:
raised TYPES.INTERNAL_ERROR : trans-chap7.adb:1473
Load address: 0x290000
Call stack traceback locations:
0x5a41ce 0x5ac5d5 0x5ac23e 0x5f0571 0x5f0656 0x5f0ca2 0x5f14fe 0x5f2c36 0x5f2d83 0x5f5ead 0x5fafcf 0x5c04d2 0x5b5f50 0x5c4cbb 0x5bf107 0x602b49 0x54e863 0x48b6c5 0x60581a 0x292db6 0x291384 0x7651fa27 0x773f7a7c 0x773f7a4c
******************************************************************
```

**Comment by tgingold** [comment] 2022-05-12 04:25
Thank you for the small testcase.  It's an issue due to concatenation of unbounded arrays.
I will implement it.

**Comment by bradley-harden-apl** [comment] 2022-08-09 19:45
@tgingold, would you expect to see this crash only in `llvm` and `gcc` backends but not `mcode`? That's what I'm seeing. I wonder if the `mcode` version somehow makes it through analysis when it shouldn't, which is causing the errors in #2154. Does that make any sense?

**Comment by bradleyharden** [comment] 2022-08-09 19:47
@tgingold, would you expect to see this crash only in `llvm` and `gcc` backends but not `mcode`? That's what I'm seeing. I wonder if the `mcode` version somehow makes it through analysis when it shouldn't, which is causing the errors in #2154. Does that make any sense?

**Comment by tgingold** [comment] 2022-08-09 19:50
Yes, this is expected.  mcode generated code only at elaboration.

**Comment by bradleyharden** [comment] 2022-08-09 19:51
Ah ok, then #2154 is likely an effective duplicate of this issue?

**Closed** 2022-08-11 04:52 UTC
Labels: Bug, FeaReq: VHDL-2008 (unconst. arrrays/records)
