### ISSUE TITLE
MinGW on Windows produces '*.dll.exe' files

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#565] opened 2018-05-01 19:37 UTC
I'm trying to improve parts of the MinGW64 compilation results. While doing so, I found that normal compilation is creating these files:

* `ghdl_llvm.exe` - **OK**
* `ghdl1-llvm.exe` - **OK**
* `libghdlvpi.dll` - **OK**
* `libghdl.dll.exe`
* `libghdl-0_36_dev.dll.exe`

I assume the last two files should have the extension `*.dll` instead of `*.dll.exe`, right?

**Comment by Paebbels** [comment] 2018-11-26 01:04
This bug still exists.

```
[...]
gnatbind -aI. -aOC:\git\GitHub\Paebbels\ghdl\build\mingw64-llvm70\pic -aI../../src -aI../../src/vhdl -aI../../src/grt -aI../../src/psl -aI../../src/vhdl/translate -aI../../src/vhdl/python -aI../../src/ghdldrv -shared -Llibghdl_ -z -x C:\git\GitHub\Paebbels\ghdl\build\mingw64-llvm70\pic\libghdl.ali
gnatlink C:\git\GitHub\Paebbels\ghdl\build\mingw64-llvm70\pic\libghdl.ali -shared-libgcc -o libghdl-0_36_dev.dll.exe -g -shared
```

**Comment by eine** [comment] 2020-01-14 07:35
@Paebbels, I think that #1010 was a duplicate of this issues, but we didn't see it. Anyway, this should be fixed. Can you confirm?

**Closed** 2020-05-10 09:25 UTC
Labels: Backend: LLVM, Bug, Build: MinGW (Makefile), Fixed in development version
